### PR TITLE
Use webcomponents-loader.js instead of -lite.js

### PR DESCRIPTION
**Pull request by jouni**
As far as I know, the `-lite.js` version is deprecated, and you should rather use the `-bundle.js` version if you really want to load the polyfills for all browsers. But the best practice is to use the `-loader.js` so that only the browsers needing the polyfills end up loading them.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-app-layout/55)

### CODE REVIEW

**Comment by jouni** [comment]
Note, I did not actually test this locally. I’m expecting the build to fail if there’s a problem (shame on me).

**Comment by alvarezguille** [comment]
Should be changed in `vaadin-element-skeleton` also

**Comment by web-padawan** [comment]
@jouni the Polymer 2 compatible version which we use won't drop `-lite.js` but I think for demos we could change this. Not sure how much it affects CDN demos, probably shouldn't break anything.

In the tests we still need to use  `-lite.js` for now, and modulizer converts it to `-bundle.js`

**Comment by alvarezguille** [comment]
Closing this stale PR, sorry it was overlooked for a long while, let's do this change in skeleton first

**Pull request closed without merging**
